---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cloudera

Repo to provide a CML template to build images suitable to `R` users when:

+ No `sudo` access is provided on CML for users to install `ubuntu` libs.
+ You want minimize setup time for advanced users with the following libraries pre-installed:

```{r, echo=FALSE}

p <- sort(c("rmarkdown",
       "bizdays",
       "broom","broom.mixed",
       "caTools",
       "corrr","corrplot",
       "curl","RCurl",
       "data.table",
       "data.tree",
       "devtools","doParallel",
       "DiagrammeR","data.tree",
       "rugarch","fGarch","fmsb",
       "filesstrings","here",
       "kableExtra",
       "formatR","patchwork","gt","ggthemes","ggtext","gganimate","ggridges","scales","ggraph","igraph","gridtext","ggpubr","tufte","VennDiagram",
       "golem", "desc","usethis",
       "gifski", "Hmisc",
       "caret","parsnip","glmnet","janitor","recipes","ranger","randomForest","anomalize","rpart.plot",
       "here",
       "htmltools","htmlwidgets",
       "httr","jsonlite","magrittr","vembedr","XML","webshot","png","Cairo","widgetframe","magick",
       "mongolite" ,"aws.s3","rhandsontable","shinycustomloader","wrapr",
       "leaflet","tidygeocoder","rgdal","sp",
       "lpSolve","lpSolveAPI","optimx",
       "knitr","shiny",
       "lubridate",
       "moments","fitdistrplus","splines2",
       "openxlsx",
       "plotly","prettydoc","GGally","ggcorrplot","ggfortify","gganimate",
       "prophet","e1071","naivebayes","splines2",
       "revealjs","rstanarm",
       "rjson","rvest","stringi","NLP","tidytext","textdata","lexicon","wordcloud2","robotstxt","tm","twitteR","rtweet","tm.plugin.webmining","widyr",
       "riem",
       "rlang","lobstr",
       "sde","skimr",
       "tidyverse","slider","tidyquant","tidymodels","feasts","timetk",
       "xlsx"))
p
```


